//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreLib.Inventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvItemSpec_Steel
    {
        public int Id { get; set; }
        public int InvItemId { get; set; }
        public string SpecFor { get; set; }
        public string SizeValue { get; set; }
        public string SizeDesc { get; set; }
        public string WtValue { get; set; }
        public string WtDesc { get; set; }
        public string SpecInfo { get; set; }
    
        public virtual InvItem InvItem { get; set; }
    }
}
