//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreLib.Inventory.Models
{
    using System;
    using System.Collections.Generic;

    public partial class InvItemSpec_Steel
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public int InvItemId { get; set; }
        public int SteelMainCatId { get; set; }
        public int SteelSubCatId { get; set; }
        public int SteelBrandId { get; set; }
        public int SteelMaterialId { get; set; }
        public int SteelOriginId { get; set; }
        public int SteelMaterialGradeId { get; set; }
        public int SteelSizeId { get; set; }
        public decimal WtKgm { get; set; }
        public decimal WtKgpc { get; set; }

        public virtual InvItem InvItem { get; set; }
        public virtual SteelMainCat SteelMainCat { get; set; }
        public virtual SteelSubCat SteelSubCat { get; set; }
        public virtual SteelBrand SteelBrand { get; set; }
        public virtual SteelMaterial SteelMaterial { get; set; }
        public virtual SteelOrigin SteelOrigin { get; set; }
        public virtual SteelMaterialGrade SteelMaterialGrade { get; set; }
        public virtual SteelSize SteelSize { get; set; }
    }
}
