//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreLib.Inventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvRequestItem
    {
        public int Id { get; set; }
        public int InvItemId { get; set; }
        public int InvRequestHdrId { get; set; }
        public int InvUomId { get; set; }
        public string ItemQty { get; set; }
        public int InvRecItemId { get; set; }
    
        public virtual InvItem InvItem { get; set; }
        public virtual InvRequestHdr InvRequestHdr { get; set; }
        public virtual InvUom InvUom { get; set; }
        public virtual InvRecItem InvRecItem { get; set; }
    }
}
