//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreLib.Inventory.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvAdjHdr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvAdjHdr()
        {
            this.InvAdjItems = new HashSet<InvAdjItem>();
        }
    
        public int Id { get; set; }
        public int InvStoreId { get; set; }
        public string dtAdj { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
    
        public virtual InvStore InvStore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvAdjItem> InvAdjItems { get; set; }
    }
}
