//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreLib.Inventory.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvStoreUser
    {
        public int Id { get; set; }
        public string InvStoreUserId { get; set; }
        public int InvStoreId { get; set; }
    
        public virtual InvStore InvStore { get; set; }
    }
}
