//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreLib.Inventory.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvTrxDtlOperator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvTrxDtlOperator()
        {
            this.InvTrxDtls = new HashSet<InvTrxDtl>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string Operator { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvTrxDtl> InvTrxDtls { get; set; }
    }
}
