//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDBSchema.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InvDBContainer : DbContext
    {
        public InvDBContainer()
            : base("name=InvDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<InvItem> InvItems { get; set; }
        public virtual DbSet<InvItemClass> InvItemClasses { get; set; }
        public virtual DbSet<InvClassification> InvClassifications { get; set; }
        public virtual DbSet<InvSupplier> InvSuppliers { get; set; }
        public virtual DbSet<InvSupplierItem> InvSupplierItems { get; set; }
        public virtual DbSet<InvStore> InvStores { get; set; }
        public virtual DbSet<InvPoHdr> InvPoHdrs { get; set; }
        public virtual DbSet<InvPoItem> InvPoItems { get; set; }
        public virtual DbSet<InvRecHdr> InvRecHdrs { get; set; }
        public virtual DbSet<InvRecItem> InvRecItems { get; set; }
        public virtual DbSet<InvRequestHdr> InvRequestHdrs { get; set; }
        public virtual DbSet<InvRequestItem> InvRequestItems { get; set; }
        public virtual DbSet<InvAdjHdr> InvAdjHdrs { get; set; }
        public virtual DbSet<InvAdjItem> InvAdjItems { get; set; }
        public virtual DbSet<InvUom> InvUoms { get; set; }
        public virtual DbSet<InvTrxHdr> InvTrxHdrs { get; set; }
        public virtual DbSet<InvTrxDtl> InvTrxDtls { get; set; }
        public virtual DbSet<InvTrxType> InvTrxTypes { get; set; }
        public virtual DbSet<InvPoHdrStatus> InvPoHdrStatus { get; set; }
        public virtual DbSet<InvTrxHdrStatus> InvTrxHdrStatus { get; set; }
        public virtual DbSet<InvTrxDtlOperator> InvTrxDtlOperators { get; set; }
        public virtual DbSet<InvStoreUser> InvStoreUsers { get; set; }
        public virtual DbSet<InvUomConversion> InvUomConversions { get; set; }
        public virtual DbSet<InvUomConvItem> InvUomConvItems { get; set; }
        public virtual DbSet<InvWarningLevel> InvWarningLevels { get; set; }
        public virtual DbSet<InvWarningType> InvWarningTypes { get; set; }
        public virtual DbSet<InvCategory> InvCategories { get; set; }
        public virtual DbSet<InvItemSpec_Steel> InvItemSpec_Steel { get; set; }
        public virtual DbSet<InvItemSysDefinedSpecs> InvItemSysDefinedSpecs { get; set; }
    }
}
