//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDBSchema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvItemSysDefinedSpecs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvItemSysDefinedSpecs()
        {
            this.InvCategorySpecDefs = new HashSet<InvCategorySpecDef>();
        }
    
        public int Id { get; set; }
        public string SpecName { get; set; }
        public string SpecCode { get; set; }
        public string SpecGroup { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvCategorySpecDef> InvCategorySpecDefs { get; set; }
    }
}
