//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDBSchema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvItemSysDefinedSpecs
    {
        public int Id { get; set; }
        public string SpecName { get; set; }
        public string SpecCode { get; set; }
        public string SpecGroup { get; set; }
        public int InvCategoryId { get; set; }
    
        public virtual InvCategory InvCategory { get; set; }
    }
}
