//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDBSchema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvPoHdr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvPoHdr()
        {
            this.InvPoItems = new HashSet<InvPoItem>();
            this.InvPoApprovals = new HashSet<InvPoApproval>();
        }
    
        public int Id { get; set; }
        public int InvSupplierId { get; set; }
        public int InvStoreId { get; set; }
        public System.DateTime DtPo { get; set; }
        public string UserId { get; set; }
        public int InvPoHdrStatusId { get; set; }
    
        public virtual InvSupplier InvSupplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvPoItem> InvPoItems { get; set; }
        public virtual InvStore InvStore { get; set; }
        public virtual InvPoHdrStatus InvPoHdrStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvPoApproval> InvPoApprovals { get; set; }
    }
}
