//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDBSchema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvSupplierItem
    {
        public int Id { get; set; }
        public int InvSupplierId { get; set; }
        public int InvItemId { get; set; }
        public string Remarks { get; set; }
        public decimal Price { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public string LeadTime { get; set; }
        public string UserId { get; set; }
    
        public virtual InvSupplier InvSupplier { get; set; }
        public virtual InvItem InvItem { get; set; }
    }
}
