//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDBSchema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvTrxHdr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvTrxHdr()
        {
            this.InvTrxDtls = new HashSet<InvTrxDtl>();
            this.InvTrxApprovals = new HashSet<InvTrxApproval>();
        }
    
        public int Id { get; set; }
        public int InvStoreId { get; set; }
        public System.DateTime DtTrx { get; set; }
        public string UserId { get; set; }
        public string Remarks { get; set; }
        public int InvTrxTypeId { get; set; }
        public int InvTrxHdrStatusId { get; set; }
        public string Party { get; set; }
    
        public virtual InvStore InvStore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvTrxDtl> InvTrxDtls { get; set; }
        public virtual InvTrxType InvTrxType { get; set; }
        public virtual InvTrxHdrStatus InvTrxHdrStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvTrxApproval> InvTrxApprovals { get; set; }
    }
}
