//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDBSchema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvTrxDtlxItemMaster
    {
        public int Id { get; set; }
        public int InvTrxDtlId { get; set; }
        public int InvItemMasterId { get; set; }
    
        public virtual InvTrxDtl InvTrxDtl { get; set; }
        public virtual InvItemMaster InvItemMaster { get; set; }
    }
}
