//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDBSchema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvTrxDtl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvTrxDtl()
        {
            this.InvTrxDtlxItemMasters = new HashSet<InvTrxDtlxItemMaster>();
        }
    
        public int Id { get; set; }
        public int InvTrxHdrId { get; set; }
        public int InvUomId { get; set; }
        public int ItemQty { get; set; }
        public int InvItemId { get; set; }
        public int InvTrxDtlOperatorId { get; set; }
        public string LotNo { get; set; }
        public string BatchNo { get; set; }
        public string Remarks { get; set; }
    
        public virtual InvTrxHdr InvTrxHdr { get; set; }
        public virtual InvUom InvUom { get; set; }
        public virtual InvItem InvItem { get; set; }
        public virtual InvTrxDtlOperator InvTrxDtlOperator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvTrxDtlxItemMaster> InvTrxDtlxItemMasters { get; set; }
    }
}
