//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDBSchema.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("InvUomConvItems")]
    public partial class InvUomConvItem
    {
        public int Id { get; set; }
        public int InvUomConversionId { get; set; }
        public Nullable<int> InvClassificationId { get; set; }
        public Nullable<int> InvItemId { get; set; }
    
        public virtual InvUomConversion InvUomConversion { get; set; }
        public virtual InvClassification InvClassification { get; set; }
        public virtual InvItem InvItem { get; set; }
    }
}
