//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDBSchema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RptReportRoles
    {
        public int Id { get; set; }
        public int ReportId { get; set; }
        public int AspNetRoleId { get; set; }
        public int RptAccessTypeId { get; set; }
    
        public virtual RptAccessType RptAccessType { get; set; }
    }
}
