//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealSys.CoreLib.Models.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public byte[] LayoutData { get; set; }
        public virtual ICollection<RptReportUser> RptReportUsers { get; set; }
        public virtual ICollection<RptReportRoles> RptReportRoles { get; set; }
        public virtual ICollection<RptReportCat> RptReportCats { get; set; }

    }
}
