//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDBSchema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvRecHdr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvRecHdr()
        {
            this.InvRecItems = new HashSet<InvRecItem>();
        }
    
        public int Id { get; set; }
        public int InvStoreId { get; set; }
        public int InvSupplierId { get; set; }
        public string DtRec { get; set; }
        public string Status { get; set; }
        public string UserId { get; set; }
    
        public virtual InvStore InvStore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvRecItem> InvRecItems { get; set; }
        public virtual InvSupplier InvSupplier { get; set; }
    }
}
